use_frameworks!
target 'NoOptionalInterpolation_Tests' do
  pod 'NoOptionalInterpolation', :path => '../'
  
  pod 'Quick', :git => 'https://github.com/Quick/Quick.git', :branch => 'swift-3.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
