osx_image: xcode7.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods --no-document
- pod repo update
- pod install --project-directory=Example
script:
- xcodebuild -scheme NoOptionalInterpolation-Example -workspace Example/NoOptionalInterpolation.xcworkspace -sdk iphonesimulator9.3 -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.3' build test | xcpretty
- pod lib lint
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'NoOptionalInterpolation'
